import * as Crypto from "expo-crypto";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { AccessibilityInfo, FlatList, StyleSheet, View } from "react-native";

import { StaffApiError } from "@/api/errors";
import { staffApi } from "@/app-services";
import { AppText, Banner, Button, Card, Confirmation, ErrorState, FilterChip, Inline, KeyValueRow, Loading, SectionHeader, TextField, spacing, useResponsiveLayout, useTheme } from "@/design-system";
import { queryClient } from "@/query/query-client";
import { queryKeys } from "@/query/query-keys";

const actions = ["RECEIPT", "POSITIVE_CORRECTION", "NEGATIVE_CORRECTION", "DAMAGE", "WASTAGE"] as const;
const actionLabels: Record<typeof actions[number], string> = { RECEIPT: "Receive stock", POSITIVE_CORRECTION: "Increase correction", NEGATIVE_CORRECTION: "Decrease correction", DAMAGE: "Record damage", WASTAGE: "Record wastage" };

export default function InventoryDetailScreen() {
  const { productId = "" } = useLocalSearchParams<{ productId: string }>(); const theme = useTheme(); const { horizontalPadding, expanded } = useResponsiveLayout();
  const [type, setType] = useState<typeof actions[number]>("RECEIPT"); const [quantity, setQuantity] = useState(""); const [reason, setReason] = useState(""); const [confirming, setConfirming] = useState(false); const [idempotencyKey, setIdempotencyKey] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  const product = useQuery({ queryKey: queryKeys.product(productId), queryFn: ({ signal }) => staffApi.product(productId, signal) });
  const movements = useQuery({ queryKey: queryKeys.movements(productId), queryFn: ({ signal }) => staffApi.movements(productId, undefined, signal) });
  const mutation = useMutation({ mutationFn: () => staffApi.adjustInventory(productId, type, quantity, reason.trim(), product.data!.inventory_version, idempotencyKey ?? Crypto.randomUUID()), onSuccess: (result) => { queryClient.setQueryData(queryKeys.product(productId), result.balance); void queryClient.invalidateQueries({ queryKey: queryKeys.movements(productId) }); void queryClient.invalidateQueries({ queryKey: queryKeys.inventorySummary }); void queryClient.invalidateQueries({ queryKey: ["staff", "products"] }); setQuantity(""); setReason(""); setConfirming(false); setIdempotencyKey(null); setMessage("Inventory balance updated."); AccessibilityInfo.announceForAccessibility("Inventory balance updated."); }, onError: async (error) => { setConfirming(false); const apiError = error instanceof StaffApiError ? error : null; if (apiError?.ambiguous || ["network_error", "timeout"].includes(apiError?.code ?? "")) { setMessage("The result is unknown. Retry the same adjustment safely or refresh the balance."); return; } setIdempotencyKey(null); if (["stale_inventory_version", "conflict"].includes(apiError?.code ?? "")) { await product.refetch(); setMessage("Another change updated this balance. Review the latest values before submitting again."); return; } setMessage(apiError?.message ?? "The adjustment could not be completed."); } });
  if (product.isPending || movements.isPending) return <Loading label="Loading inventory" />; if (!product.data || !movements.data) return <ErrorState title="Inventory unavailable" action={<Button label="Retry" onPress={() => { void product.refetch(); void movements.refetch(); }} />} />;
  const valid = /^\d+(\.\d+)?$/.test(quantity) && !/^0*(\.0+)?$/.test(quantity) && reason.trim().length > 0; const reduction = ["NEGATIVE_CORRECTION", "DAMAGE", "WASTAGE"].includes(type);
  const changeInput = () => { setIdempotencyKey(null); setMessage(null); };
  const begin = () => { const key = idempotencyKey ?? Crypto.randomUUID(); setIdempotencyKey(key); setConfirming(true); };
  const header = <View style={[styles.header, { paddingHorizontal: horizontalPadding }]}><AppText variant="titleLarge" weight="bold">{product.data.product.name}</AppText>{message ? <Banner tone={mutation.isError ? "warning" : "success"} message={message} action={idempotencyKey && mutation.isError ? <Button variant="secondary" label="Retry same adjustment" onPress={() => mutation.mutate()} /> : undefined} /> : null}<View style={expanded ? styles.columns : styles.stack}><Card variant="tonal"><SectionHeader title="Current balance" /><KeyValueRow label="Sellable" value={`${product.data.sellable_quantity} ${product.data.product.unit}`} primary /><KeyValueRow label="On hand" value={`${product.data.on_hand_quantity} ${product.data.product.unit}`} /><KeyValueRow label="Reserved" value={`${product.data.reserved_quantity} ${product.data.product.unit}`} /><AppText color="secondary">Stock cannot be reduced below reserved quantity.</AppText></Card><View style={[styles.form, expanded ? styles.flex : undefined]}><SectionHeader title="Adjustment" /><AppText variant="labelLarge" weight="semibold">Movement type</AppText><View style={styles.chips}>{actions.map((action) => <FilterChip key={action} label={actionLabels[action]} selected={type === action} onPress={() => { setType(action); changeInput(); }} />)}</View><TextField label={`Quantity (${product.data.product.unit})`} required value={quantity} onChangeText={(value) => { setQuantity(value); changeInput(); }} keyboardType="decimal-pad" /><TextField label="Reason" required value={reason} onChangeText={(value) => { setReason(value); changeInput(); }} multiline /><Button variant={reduction ? "secondary" : "primary"} label="Review adjustment" disabled={!valid} onPress={begin} /></View></View><SectionHeader title="Recent movements" /></View>;
  return <><FlatList style={{ backgroundColor: theme.colors.background }} data={movements.data.items} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListHeaderComponent={header} renderItem={({ item }) => <View style={[styles.movement, { marginHorizontal: horizontalPadding }]}><View style={[styles.dot, { backgroundColor: item.on_hand_delta.startsWith("-") ? theme.colors.warning : theme.colors.info }]} /><View style={styles.flex}><Inline between wrap><AppText weight="bold">{item.movement_type.replaceAll("_", " ")}</AppText><AppText color={item.on_hand_delta.startsWith("-") ? "warning" : "info"} weight="bold">{item.on_hand_delta.startsWith("-") ? "" : "+"}{item.on_hand_delta} {product.data.product.unit}</AppText></Inline><AppText>On hand {item.on_hand_before} → {item.on_hand_after}; reserved {item.reserved_before} → {item.reserved_after}</AppText><AppText>{item.reason}</AppText><AppText color="secondary">{item.actor_type} · {new Date(item.created_at).toLocaleString()}</AppText></View></View>} ItemSeparatorComponent={() => <View style={styles.separator} />} />
    <Confirmation visible={confirming} title="Confirm stock adjustment" message={`${product.data.product.name} · ${actionLabels[type]} · ${quantity} ${product.data.product.unit}. Current sellable balance is ${product.data.sellable_quantity} ${product.data.product.unit}.`} confirmLabel="Apply adjustment" danger={type === "DAMAGE" || type === "WASTAGE"} busy={mutation.isPending} onConfirm={() => mutation.mutate()} onCancel={() => setConfirming(false)}><AppText color={reduction ? "warning" : "secondary"}>{reduction ? "This action reduces physical stock." : "This action increases physical stock."}</AppText></Confirmation></>;
}
const styles = StyleSheet.create({ list: { width: "100%", maxWidth: 1440, alignSelf: "center", paddingVertical: spacing[4], paddingBottom: spacing[10] }, header: { gap: spacing[4], marginBottom: spacing[4] }, stack: { gap: spacing[4] }, columns: { flexDirection: "row", alignItems: "flex-start", gap: spacing[6] }, form: { gap: spacing[3] }, flex: { flex: 1 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: spacing[2] }, movement: { flexDirection: "row", gap: spacing[3] }, dot: { width: 12, height: 12, borderRadius: 6, marginTop: spacing[1] }, separator: { height: spacing[4] } });
