import * as Crypto from "expo-crypto";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { Alert, ScrollView, Text, View } from "react-native";
import { staffApi } from "@/app-services";
import { StaffApiError } from "@/api/errors";
import { Button, Card, Field, Loading, Screen, StateMessage, dsStyles } from "@/components/design-system";
import { spacing, useTheme } from "@/components/design-system/theme";
import { queryClient } from "@/query/query-client";
import { queryKeys } from "@/query/query-keys";
const actions = ["RECEIPT", "POSITIVE_CORRECTION", "NEGATIVE_CORRECTION", "DAMAGE", "WASTAGE"] as const;
export default function InventoryDetailScreen() {
  const { productId = "" } = useLocalSearchParams<{ productId: string }>(); const theme = useTheme();
  const [type, setType] = useState<typeof actions[number]>("RECEIPT"); const [quantity, setQuantity] = useState(""); const [reason, setReason] = useState(""); const [confirmed, setConfirmed] = useState(false); const [key, setKey] = useState<string | null>(null);
  const product = useQuery({ queryKey: queryKeys.product(productId), queryFn: ({ signal }) => staffApi.product(productId, signal) });
  const movements = useQuery({ queryKey: queryKeys.movements(productId), queryFn: ({ signal }) => staffApi.movements(productId, undefined, signal) });
  const mutation = useMutation({ mutationFn: () => staffApi.adjustInventory(productId, type, quantity, reason.trim(), product.data!.inventory_version, key ?? Crypto.randomUUID()), onSuccess: (result) => { queryClient.setQueryData(queryKeys.product(productId), result.balance); void queryClient.invalidateQueries({ queryKey: queryKeys.movements(productId) }); void queryClient.invalidateQueries({ queryKey: queryKeys.inventorySummary }); void queryClient.invalidateQueries({ queryKey: ["staff", "products"] }); setQuantity(""); setReason(""); setConfirmed(false); setKey(null); }, onError: (error) => { setConfirmed(false); if (!(error instanceof StaffApiError) || !["network_error", "timeout"].includes(error.code)) setKey(null); } });
  if (product.isPending || movements.isPending) return <Screen><Loading label="Loading inventory" /></Screen>; if (!product.data || !movements.data) return <Screen><StateMessage title="Inventory unavailable" /></Screen>;
  const valid = /^\d+(\.\d+)?$/.test(quantity) && !/^0*(\.0+)?$/.test(quantity) && reason.trim().length > 0;
  const submit = () => { const id = key ?? Crypto.randomUUID(); setKey(id); Alert.alert("Confirm stock adjustment", `${product.data!.product.name}\n${type.replaceAll("_", " ")} ${quantity} ${product.data!.product.unit}`, [{ text: "Cancel", style: "cancel" }, { text: "Confirm", style: type === "RECEIPT" || type === "POSITIVE_CORRECTION" ? "default" : "destructive", onPress: () => { setConfirmed(true); mutation.mutate(); } }]); };
  return <Screen><ScrollView contentContainerStyle={{ padding: spacing.md, gap: spacing.md }} keyboardShouldPersistTaps="handled"><Text style={[dsStyles.title, { color: theme.text }]}>{product.data.product.name}</Text><Card><Text style={{ color: theme.text }}>On hand {product.data.on_hand_quantity} · Reserved {product.data.reserved_quantity} · Sellable {product.data.sellable_quantity} {product.data.product.unit}</Text><Text style={{ color: theme.muted }}>Inventory version {product.data.inventory_version}</Text></Card><Text style={[dsStyles.heading, { color: theme.text }]}>Adjustment</Text><View style={{ gap: spacing.sm }}>{actions.map((action) => <Button key={action} variant={type === action ? "primary" : "secondary"} label={action.replaceAll("_", " ")} onPress={() => { setType(action); setKey(null); }} />)}</View><Field label={`Quantity (${product.data.product.unit})`} value={quantity} onChangeText={(value) => { setQuantity(value); setKey(null); }} keyboardType="decimal-pad" /><Field label="Reason" value={reason} onChangeText={(value) => { setReason(value); setKey(null); }} multiline /><Text style={{ color: theme.muted }}>Stock cannot be reduced below reserved quantity {product.data.reserved_quantity}.</Text><Button label="Review and confirm" disabled={!valid || mutation.isPending || confirmed} onPress={submit} /><Text style={[dsStyles.heading, { color: theme.text }]}>Recent movements</Text>{movements.data.items.map((movement) => <Card key={movement.id}><Text style={{ color: theme.text }}>{movement.movement_type.replaceAll("_", " ")} · {movement.quantity} {product.data!.product.unit}</Text><Text style={{ color: theme.text }}>On hand {movement.on_hand_before} → {movement.on_hand_after}; reserved {movement.reserved_before} → {movement.reserved_after}</Text><Text style={{ color: theme.muted }}>{movement.reason} · {new Date(movement.created_at).toLocaleString()}</Text></Card>)}</ScrollView></Screen>;
}
